<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="generator" content="O2System PHP Framework">

	<!-- Font Awesome -->
	<link rel="stylesheet" href="<?php echo $this->getAssetsUrl( 'fonts/font-awesome.css', TRUE ); ?>">

	<title><?php echo $header; ?></title>

	<style type="text/css" media="screen">
		body {
		    font-family: 'Ubuntu', "Trebuchet MS", Verdana, sans-serif;
		    font-size: 12px;
		}
		*, *::after, *::before {
		    -webkit-box-sizing: border-box;
		    -moz-box-sizing: border-box;
		    box-sizing: border-box;
		}
		.h1, .h2, .h3, .h4, .h5, .h6, h1, h2, h3, h4, h5, h6 {
		    font-family: inherit;
		    font-weight: 500;
		    line-height: 1.1;
		    color: inherit;
		}
		.container-fluid {
		    padding-right: 15px;
		    padding-left: 15px;
		    margin-right: auto;
		    margin-left: auto;
		}
		.row {
		    margin-right: -15px;
		    margin-left: -15px;
		}
		.container-fluid::before, .container-fluid::after, .row::before, .row::after{
		    display: table;
		    content: " ";
		}
		.container-fluid::after, .row::after{
			clear: both;
		}
		.col-md-12{
		    position: relative;
		    min-height: 1px;
		    padding-right: 15px;
		    padding-left: 15px;
		    width:  100%;
		    float: left;
		}
		.error-wrapper {
		    font-size: 12px;
		    color: #303641;
		    margin: 50px;
		}
		* {
		    margin: 0px;
		    padding: 0px;
		}
		a {
		    text-decoration: none !important;
		}
		h1 {
		    font-size: 24px;
		    color: #e73d2f;
		    text-transform: uppercase;
		    padding: 20px 0px 0px 0px;
		    margin: 0;
		}
		h2 {
		    font-size: 20px;
		    text-transform: uppercase;
		    margin: 0;
		}
		p {
		    font-size: 14px;
		    padding: 10px 0px;
		    font-weight: 400;
		}
		p.error-text {
		    color: #e73d2f;
		    font-weight: 800;
		    margin: 10px 0px;
		    font-size: 16px;
		}
		.copyright {
		    font-weight: 400;
		    font-size: 12px;
		    text-transform: uppercase;
		}
		small {
		    font-size: 10px;
		    text-transform: uppercase;
		}
		.sql-query {
		    max-width: 500px;
		    margin: 5px 0px 20px 0px;
		    padding: 16px;
		    overflow: auto;
		    line-height: 1.45;
		    background-color: #f7f7f7;
		    border-radius: 3px;
		}
		ol.backtrace {
		    margin: 1px 15px 15px 15px;
		    font-size: 14px;
		}
		ol.backtrace li {
		    padding-left: 10px;
		    line-height: 1.5;
		    margin-bottom: 10px;
		}
		ol.backtrace .fa {
		    width: 14px;
		}
	</style>
</head>
<body>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="error-wrapper">
				<img src="<?php echo $this->getAssetsUrl( 'images/logo/o2system.png', TRUE ); ?>" height="50"/>

				<h1><?php echo $header; ?></h1>

				<h2><?php echo $description; ?><?php echo( $exception->getCode() == 0 ? '' : '(' . $exception->getCode() . ')' ); ?></h2>

				<p class="error-text"><?php echo $exception->getMessage(); ?></p>


				<ol class="backtrace">

					<?php foreach ( $trace->chronology() as $chronology ): ?>
						<li>
							<i class="fa fa-code"></i> <?php echo $chronology->call; ?><br>
							<i class="fa fa-file-code-o"></i> <?php echo @realpath( $chronology->file ); ?><br>
							<i class="fa fa-list-ol"></i> <?php echo $chronology->line; ?>
						</li>
					<?php endforeach ?>

				</ol>

			</div>
		</div>
	</div>
</div>
</body>
</html>