<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="generator" content="O2System PHP Framework">

	<!-- Font Awesome -->
	<link rel="stylesheet" href="<?php echo $exception->getAssetsUrl( 'fonts/font-awesome.css', TRUE ); ?>">

	<title><?php echo $exception->getHeader(); ?></title>

	<style type="text/css" media="screen">
		body {
            font-family: "Ubuntu", "Segoe UI", "Trebuchet", sans-serif;
		    font-size: 12px;
		}
		*, *::after, *::before {
		    -webkit-box-sizing: border-box;
		    -moz-box-sizing: border-box;
		    box-sizing: border-box;
		}

        * {
            margin: 0px;
            padding: 0px;
        }

        a {
            text-decoration: none !important;
        }
		.h1, .h2, .h3, .h4, .h5, .h6, h1, h2, h3, h4, h5, h6 {
		    font-family: inherit;
            font-weight: normal;
		    line-height: 1.1;
		    color: inherit;
		}
		.container-fluid {
		    padding-right: 15px;
		    padding-left: 15px;
		    margin-right: auto;
		    margin-left: auto;
		}
		.row {
		    margin-right: -15px;
		    margin-left: -15px;
		}
		.container-fluid::before, .container-fluid::after, .row::before, .row::after{
		    display: table;
		    content: " ";
		}
		.container-fluid::after, .row::after{
			clear: both;
		}
		.col-md-12{
		    position: relative;
		    min-height: 1px;
		    padding-right: 15px;
		    padding-left: 15px;
		    width:  100%;
		    float: left;
		}
		.error-wrapper {
		    font-size: 12px;
		    color: #303641;
		    margin: 50px;
		}

        h1.exception-header {
            font-size: 20px;
            font-weight: normal;
		    color: #e73d2f;
		    text-transform: uppercase;
            padding: 10px 0px 0px 0px;
		    margin: 0;
		}

        h2.exception-description {
            color: #c5c5c5;
            font-size: 14px;
            font-style: italic;
            font-weight: normal;
            text-transform: capitalize;
            padding: 5px 0px 0px 0px;
		    margin: 0;
		}

        p.exception-message {
            text-transform: capitalize;
            color: #444444;
            font-weight: normal;
            margin: 20px 0px;
		    font-size: 14px;
		}

        ol.exception-chronology {
            color: #444444;
		    margin: 1px 15px 15px 15px;
            font-size: 11px;
		}

        ol.exception-chronology li {
		    padding-left: 10px;
		    line-height: 1.5;
		    margin-bottom: 10px;
		}

        ol.exception-chronology li span.exception-chronology-file {
            color: #c5c5c5;
            font-size: 10px;
            font-style: italic;
		}
	</style>
</head>
<body>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="error-wrapper">
				<img src="<?php echo $exception->getAssetsUrl( 'images/logo/o2system.png', TRUE ); ?>" height="50"/>
                <h1 class="exception-header"><?php echo $exception->getHeader(); ?></h1>
                <h2 class="exception-description"><?php echo $exception->getDescription(); ?>
                    (<?php echo $exception->getCode(); ?>)</h2>
                <p class="exception-message"><?php echo $exception->getMessage(); ?></p>
                <ol class="exception-chronology">
					<?php foreach ( $exception->getChronology() as $chronology ): ?>
						<li>
                            <span class="exception-chronology-function"><?php echo $chronology->call; ?></span><br>
                            <span class="exception-chronology-file"><?php echo @realpath( $chronology->file ); ?>
                                :<?php echo $chronology->line; ?></span><br>
						</li>
					<?php endforeach ?>
				</ol>
			</div>
		</div>
	</div>
</div>
</body>
</html>