<?php


namespace Tests\Services;


use O2System\Kernel\Services\Shutdown;
use PHPUnit\Framework\TestCase;

class ShutdownTest extends TestCase
{
    protected $shutdown;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->shutdown = new Shutdown();
    }

    public function testExecute()
    {
        $result = $this->shutdown->execute();
        $this->assertEquals('haha', $result);

    }

    public function testRegister()
    {
        $result = $this->shutdown->register();
        $this->assertEquals('hahah', $result);

    }

}
