<?php


namespace Tests\Services;


use O2System\Kernel\Services\Language;
use PHPUnit\Framework\TestCase;

class LanguageTest extends TestCase
{
    protected $language;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->language = new Language();
    }

    public function testDefaultLanguage()
    {
        $this->language->setDefault('id-ID');
        $lang = $this->language->getDefault();
        $this->assertEquals('id-ID', $lang);
    }

    public function testDefaultLocalLanguage()
    {
        $this->language->setDefaultLocale('id');
        $lang = $this->language->getDefaultLocale();
        $this->assertEquals('id', $lang);

    }

    public function testDefaultIdeom()
    {
        $this->language->setDefaultIdeom('ID');
        $lang = $this->language->getDefaultIdeom();
        $this->assertEquals('ID', $lang);
    }

}
